packages:
  - "."

overrides:
  "@get-air/cache": "github:get-air/cache#441041559fbd2455cad9c0aeff3c7a35e0544982"
  "@get-air/http": "github:get-air/http#20b0c9ecaea087068894c1591e5f09ca1753f5d5"

allowBuilds:
  "@get-air/cache@https://codeload.github.com/get-air/cache/tar.gz/441041559fbd2455cad9c0aeff3c7a35e0544982": true
  "@get-air/http@https://codeload.github.com/get-air/http/tar.gz/20b0c9ecaea087068894c1591e5f09ca1753f5d5": true
  esbuild: true
